### ISSUE TITLE
Loading com status da transferência do arquivo

### ISSUE THREAD

**Issue by BryanRibeiro** [TechNinjass/midall-frontend#20]
Data Início: 28/04/2023
Data Estimada: 02/05/2023

Descrição:
Fazer o loading com status da transferência do arquivo que apareça automaticamente.

DoD:
- Loading ao transferir um arquivo no sistema
- Dev Tasks concluídas
- Task revisadas pelo PO
- Erros resolvidos
- Integrações com outros componentes (ex. APIs) foi testado e funciona.
- Código já foi testado pelo QA ou, por review.
- Teste de performance/segurança do componente foi realizado e atende aos requisitos estabelecidos;

**Comment by camilaffpacheco** [comment]
Essa task depende da componentização do cabeçalho (feature-21)
